# Generated by Django 4.2.6 on 2023-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='idk', upload_to='poster'),
            preserve_default=False,
        ),
    ]
